booking/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
    path('', views.StoreList.as_view(), name='store_list'),
    path('login/', LoginView.as_view(template_name='admin/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('store/<int:pk>/staffs/', views.StaffList.as_view(), name='staff_list'),
    path('staff/<int:pk>/calendar/', views.StaffCalendar.as_view(), name='calendar'),
    path('staff/<int:pk>/calendar/<int:year>/<int:month>/<int:day>/', views.StaffCalendar.as_view(), name='calendar'),
    path('staff/<int:pk>/booking/<int:year>/<int:month>/<int:day>/<int:hour>/', views.Booking.as_view(), name='booking'),

    path('mypage/', views.MyPage.as_view(), name='my_page'),
    path('mypage/<int:pk>/', views.MyPageWithPk.as_view(), name='my_page_with_pk'),
    path('mypage/<int:pk>/calendar/', views.MyPageCalendar.as_view(), name='my_page_calendar'),
    path('mypage/<int:pk>/calendar/<int:year>/<int:month>/<int:day>/', views.MyPageCalendar.as_view(), name='my_page_calendar'),
    path('mypage/<int:pk>/config/<int:year>/<int:month>/<int:day>/', views.MyPageDayDetail.as_view(), name='my_page_day_detail'),
    path('mypage/schedule/<int:pk>/', views.MyPageSchedule.as_view(), name='my_page_schedule'),
    path('mypage/schedule/<int:pk>/delete/', views.MyPageScheduleDelete.as_view(), name='my_page_schedule_delete'),
    path('mypage/holiday/add/<int:pk>/<int:year>/<int:month>/<int:day>/<int:hour>/', views.my_page_holiday_add, name='my_page_holiday_add'),
]

fuku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
]

booking/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Store(models.Model):
    """店舗"""
    name = models.CharField('店名', max_length=255)

    def __str__(self):
        return self.name


class Staff(models.Model):
    """店舗スタッフ"""
    name = models.CharField('表示名', max_length=50)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='ログインユーザー', on_delete=models.CASCADE
    )
    store = models.ForeignKey(Store, verbose_name='店舗', on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'store'], name='unique_staff'),
        ]

    def __str__(self):
        return f'{self.store.name} - {self.name}'


class Schedule(models.Model):
    """予約スケジュール."""
    start = models.DateTimeField('開始時間')
    end = models.DateTimeField('終了時間')
    name = models.CharField('予約者名', max_length=255)
    staff = models.ForeignKey('Staff', verbose_name='スタッフ', on_delete=models.CASCADE)

    def __str__(self):
        start = timezone.localtime(self.start).strftime('%Y/%m/%d %H:%M:%S')
        end = timezone.localtime(self.end).strftime('%Y/%m/%d %H:%M:%S')
        return f'{self.name} {start} ~ {end} {self.staff}'

booking/views.py
import datetime
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import generic
from django.views.decorators.http import require_POST
from .models import Store, Staff, Schedule

User = get_user_model()


class OnlyStaffMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        staff = get_object_or_404(Staff, pk=self.kwargs['pk'])
        return staff.user == self.request.user or self.request.user.is_superuser


class OnlyScheduleMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        schedule = get_object_or_404(Schedule, pk=self.kwargs['pk'])
        return schedule.staff.user == self.request.user or self.request.user.is_superuser


class OnlyUserMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        return self.kwargs['pk'] == self.request.user.pk or self.request.user.is_superuser


class StoreList(generic.ListView):
    model = Store
    ordering = 'name'


class StaffList(generic.ListView):
    model = Staff
    ordering = 'name'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['store'] = self.store
        return context

    def get_queryset(self):
        store = self.store = get_object_or_404(Store, pk=self.kwargs['pk'])
        queryset = super().get_queryset().filter(store=store)
        return queryset


class StaffCalendar(generic.TemplateView):
    template_name = 'booking/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        staff = get_object_or_404(Staff, pk=self.kwargs['pk'])
        today = datetime.date.today()

        # どの日を基準にカレンダーを表示するかの処理。
        # 年月日の指定があればそれを、なければ今日からの表示。
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        if year and month and day:
            base_date = datetime.date(year=year, month=month, day=day)
        else:
            base_date = today

        # カレンダーは1週間分表示するので、基準日から1週間の日付を作成しておく
        days = [base_date + datetime.timedelta(days=day) for day in range(7)]
        start_day = days[0]
        end_day = days[-1]

        # 9時から17時まで1時間刻み、1週間分の、値がTrueなカレンダーを作る
        calendar = {}
        for hour in range(9, 18):
            row = {}
            for day in days:
                row[day] = True
            calendar[hour] = row

        # カレンダー表示する最初と最後の日時の間にある予約を取得する
        start_time = datetime.datetime.combine(start_day, datetime.time(hour=9, minute=0, second=0))
        end_time = datetime.datetime.combine(end_day, datetime.time(hour=17, minute=0, second=0))
        for schedule in Schedule.objects.filter(staff=staff).exclude(Q(start__gt=end_time) | Q(end__lt=start_time)):
            local_dt = timezone.localtime(schedule.start)
            booking_date = local_dt.date()
            booking_hour = local_dt.hour
            if booking_hour in calendar and booking_date in calendar[booking_hour]:
                calendar[booking_hour][booking_date] = False

        context['staff'] = staff
        context['calendar'] = calendar
        context['days'] = days
        context['start_day'] = start_day
        context['end_day'] = end_day
        context['before'] = days[0] - datetime.timedelta(days=7)
        context['next'] = days[-1] + datetime.timedelta(days=1)
        context['today'] = today
        context['public_holidays'] = settings.PUBLIC_HOLIDAYS
        return context


class Booking(generic.CreateView):
    model = Schedule
    fields = ('name',)
    template_name = 'booking/booking.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['staff'] = get_object_or_404(Staff, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        staff = get_object_or_404(Staff, pk=self.kwargs['pk'])
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        hour = self.kwargs.get('hour')
        start = datetime.datetime(year=year, month=month, day=day, hour=hour)
        end = datetime.datetime(year=year, month=month, day=day, hour=hour + 1)
        if Schedule.objects.filter(staff=staff, start=start).exists():
            messages.error(self.request, 'すみません、入れ違いで予約がありました。別の日時はどうですか。')
        else:
            schedule = form.save(commit=False)
            schedule.staff = staff
            schedule.start = start
            schedule.end = end
            schedule.save()
        return redirect('booking:calendar', pk=staff.pk, year=year, month=month, day=day)


class MyPage(LoginRequiredMixin, generic.TemplateView):
    template_name = 'booking/my_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['staff_list'] = Staff.objects.filter(user=self.request.user).order_by('name')
        context['schedule_list'] = Schedule.objects.filter(staff__user=self.request.user, start__gte=timezone.now()).order_by('name')
        return context


class MyPageWithPk(OnlyUserMixin, generic.TemplateView):
    template_name = 'booking/my_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = get_object_or_404(User, pk=self.kwargs['pk'])
        context['staff_list'] = Staff.objects.filter(user__pk=self.kwargs['pk']).order_by('name')
        context['schedule_list'] = Schedule.objects.filter(staff__user__pk=self.kwargs['pk'], start__gte=timezone.now()).order_by('name')
        return context


class MyPageCalendar(OnlyStaffMixin, StaffCalendar):
    template_name = 'booking/my_page_calendar.html'


class MyPageDayDetail(OnlyStaffMixin, generic.TemplateView):
    template_name = 'booking/my_page_day_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        staff = get_object_or_404(Staff, pk=pk)
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        date = datetime.date(year=year, month=month, day=day)

        # 9時から17時まで1時間刻みのカレンダーを作る
        calendar = {}
        for hour in range(9, 18):
            calendar[hour] = []

        # カレンダー表示する最初と最後の日時の間にある予約を取得する
        start_time = datetime.datetime.combine(date, datetime.time(hour=9, minute=0, second=0))
        end_time = datetime.datetime.combine(date, datetime.time(hour=17, minute=0, second=0))
        for schedule in Schedule.objects.filter(staff=staff).exclude(Q(start__gt=end_time) | Q(end__lt=start_time)):
            local_dt = timezone.localtime(schedule.start)
            booking_date = local_dt.date()
            booking_hour = local_dt.hour
            if booking_hour in calendar:
                calendar[booking_hour].append(schedule)

        context['calendar'] = calendar
        context['staff'] = staff
        return context


class MyPageSchedule(OnlyScheduleMixin, generic.UpdateView):
    model = Schedule
    fields = ('start', 'end', 'name')
    success_url = reverse_lazy('booking:my_page')


class MyPageScheduleDelete(OnlyScheduleMixin, generic.DeleteView):
    model = Schedule
    success_url = reverse_lazy('booking:my_page')


@require_POST
def my_page_holiday_add(request, pk, year, month, day, hour):
    staff = get_object_or_404(Staff, pk=pk)
    if staff.user == request.user or request.user.is_superuser:
        start = datetime.datetime(year=year, month=month, day=day, hour=hour)
        end = datetime.datetime(year=year, month=month, day=day, hour=hour + 1)
        Schedule.objects.create(staff=staff, start=start, end=end, name='休暇(システムによる追加)')
        return redirect('booking:my_page_day_detail', pk=pk, year=year, month=month, day=day)

    raise PermissionDenied

booking/templates/booking/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>AWASE | 第一印象で減点されない似合うを探す</title>

<!--  bootstrap core CSS  -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<!-- mystyle CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
</head>

<body>
<nav>
     {% if user.is_authenticated %}
<!--  umi navbar login  -->
        <div class="bs-component">
              <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
              <a class="navbar-brand" href="{% url 'booking:store_list' %}">AWASE</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

            <div class="collapse navbar-collapse" id="navbarColor02">
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">検索</button>
                </form>
            </div>
            <div class="collapse navbar-collapse justify-content-end" id="navbarColor02">
                  <ul class="navbar-nav" >
                    <li class="nav-item　float-right" >
                      <a class="nav-link" href="{% url 'booking:my_page' %}" >マイページ</a>
                    </li>
                    <li class="nav-item　float-right">
                      <a class="nav-link" href="#">リンク</a>
                    </li>
                    <li class="nav-item　float-right">
                      <a class="nav-link" href="#">リンク</a>
                    </li>
                   <li class="nav-item　float-right">
                      <a class="nav-link" href="{% url 'booking:logout' %}">ログアウト</a>
                    </li>
                  </ul>
            </div>
          </nav>
        </div>
     {% else %}
<!--  umi navbar not sign in -->
    <div class="bs-component">
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="{% url 'booking:store_list' %}">AWASE</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">検索</button>
            </form>
        </div>
        <div class="collapse navbar-collapse justify-content-end" id="navbarColor02">
              <ul class="navbar-nav" >
                <li class="nav-item　float-right">
                  <a class="nav-link" href="#">会員登録</a>
                </li>
                <li class="nav-item　float-right">
                  <a class="nav-link" href="{% url 'booking:login' %}">ログイン</a>
                </li>
              </ul>
        </div>
      </nav>
    </div>
     {% endif %}
<!-- umi navbar css -->
<style>
    .navbar-nav{
    text-align: right;
    }
</style>
</nav>

{% for message in messages %}
    <p> {{ message }}</p>
{% endfor %}

{% block content %}{% endblock %}

<!-- フッター -->
<footer class="py-5 bg-primary">
    <div class="container">
        <p class="m-0 text-center text-white small">Copyright &copy; AWASE</p>
    </div>
</footer>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
<!-　bootstrap core js -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

booking/templates/booking/booking.html
{% extends 'booking/base.html' %}

{% block content %}
    <h1>{{ staff.store.name }}店 {{ staff.name }}</h1>
    <p>{{ view.kwargs.year }}年{{ view.kwargs.month }}月{{ view.kwargs.day }}日 {{ view.kwargs.hour }}時に予約</p>
    <form action="" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>
{% endblock %}

booking/templates/booking/calendar.html
{% extends 'booking/base.html' %}

{% block content %}

    <h1>{{ staff.store.name }}店 {{ staff.name }}</h1>
    <p>{{ start_day }} - {{ end_day }}</p>
    <table class="table table-bordered text-center" style="table-layout: fixed;width: 100%" border="1">
        <tr>
            <td><a href="{% url 'booking:calendar' staff.pk before.year before.month before.day %}">前週</a></td>
            {% for day in days %}
                {% if day in public_holidays %}
                    <th style="background-color: yellow">{{ day | date:"d(D)" }}</th>
                {% elif day.weekday == 5 %}
                    <th style="color: blue;">{{ day | date:"d(D)" }}</th>
                {% elif day.weekday == 6 %}
                    <th style="color: red;">{{ day | date:"d(D)" }}</th>
                {% else %}
                    <th>{{ day | date:"d(D)" }}</th>
                {% endif %}
            {% endfor %}
            <td><a href="{% url 'booking:calendar' staff.pk next.year next.month next.day %}">次週</a></td>
        </tr>

        {% for hour, schedules in calendar.items %}
            <tr style="font-size:12px">
                <td>
                    {{ hour }}:00
                </td>
                {% for dt, book in schedules.items %}
                    <td>
                        {% if dt <= today %}
                            -
                        {% elif book %}
                            <a href="{% url 'booking:booking' staff.pk dt.year dt.month dt.day hour %}">○</a>
                        {% else %}
                            ×
                        {% endif %}
                    </td>

                {% endfor %}
                <td>
                    {{ hour }}:00
                </td>
            </tr>
        {% endfor %}

    </table>
{% endblock %}

booking/templates/booking/my_page.html
{% extends 'booking/base.html' %}

{% block content %}
    <h1>{{ user.username }}のMyPage</h1>
    <h2>所属店舗</h2>
    <ul>
        {% for staff in staff_list %}
            <li><a href="{% url 'booking:my_page_calendar' staff.pk %}">{{ staff }}</a></li>
        {% empty %}
            <li>まだ店舗がありません。</li>
        {% endfor %}
    </ul>

    <h2>直近の予約</h2>
    <ul>
        {% for schedule in schedule_list %}
            <li><a href="{% url 'booking:my_page_schedule' schedule.pk %}">{{ schedule }}</a></li>
        {% empty %}
            <li>予約はありません。</li>
        {% endfor %}
    </ul>
{% endblock %}

booking/templates/booking/my_page_calendar.html
{% extends 'booking/base.html' %}

{% block content %}

    <h1>{{ staff.store.name }}店 {{ staff.name }}</h1>
    <p>{{ start_day }} - {{ end_day }}</p>
    <table class="table table-bordered text-center" style="table-layout: fixed;width: 100%" border="1">
        <tr>
            <td><a href="{% url 'booking:my_page_calendar' staff.pk before.year before.month before.day %}">前週</a></td>
            {% for day in days %}
                {% if day in public_holidays %}
                    <th style="background-color: yellow">{{ day | date:"d(D)" }}
                {% elif day.weekday == 5 %}
                    <th style="color: blue;">{{ day | date:"d(D)" }}
                {% elif day.weekday == 6 %}
                    <th style="color: red;">{{ day | date:"d(D)" }}
                {% else %}
                    <th>{{ day | date:"d(D)" }}
                {% endif %}
                <br><a href="{% url 'booking:my_page_day_detail' staff.pk day.year day.month day.day %}">詳細</a>
            {% endfor %}
            <td><a href="{% url 'booking:my_page_calendar' staff.pk next.year next.month next.day %}">次週</a></td>
        </tr>

        {% for hour, schedules in calendar.items %}
            <tr style="font-size:12px">
                <td>
                    {{ hour }}:00
                </td>
                {% for dt, book in schedules.items %}
                    <td>
                        {% if book %}
                            ○
                        {% else %}
                            ×
                        {% endif %}
                    </td>

                {% endfor %}
                <td>
                    {{ hour }}:00
                </td>
            </tr>
        {% endfor %}

    </table>
{% endblock %}

booking/templates/booking/my_page_day_detail.html
{% extends 'booking/base.html' %}

{% block content %}

    <h1>{{ staff.store.name }}店 {{ staff.name }}</h1>
    <p>{{ view.kwargs.year }}年{{ view.kwargs.month }}月{{ view.kwargs.day }}日の予約一覧</p>
    <table class="table table-bordered text-center" style="table-layout: fixed;width: 100%" border="1">
        {% for hour, schedules in calendar.items %}
            <tr style="font-size:12px">
                <td>
                    {{ hour }}:00
                </td>
                <td>
                    {% if schedules %}
                        {% for s in schedules %}
                            <a href="{% url 'booking:my_page_schedule' s.pk %}">{{ s.name }}</a>
                        {% endfor %}
                    {% else %}
                        <form action="{% url 'booking:my_page_holiday_add' staff.pk view.kwargs.year view.kwargs.month view.kwargs.day hour %}"
                              method="POST">
                            {% csrf_token %}
                            <button type="submit">休暇にする</button>
                        </form>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}

    </table>
{% endblock %}

booking/templates/booking/schedule_form.html
{% extends 'booking/base.html' %}

{% block content %}

    <h1>{{ schedule.staff.store.name }}店 {{ schedule.staff.name }}</h1>
    <form action="" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>
    <hr>
    <form action="{% url 'booking:my_page_schedule_delete' schedule.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit">削除</button>
    </form>
{% endblock %}

booking/templates/booking/store_list.html
<!--　TOPページ　-->
{% extends 'booking/base.html' %}
{% load static %}

{% block content %}
<!-- TOP slide -->
<main role="main">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="first-slide" src="https://www.pakutaso.com/shared/img/thumb/KAZ19514005_TP_V.jpg" alt="First slide" height="80%" width="80%">
            </div>
            <div class="carousel-item">
                <img class="second-slide" src="https://www.pakutaso.com/shared/img/thumb/coin198192301_TP_V.jpg" alt="Second slide" height="80%" width="80%">
            </div>
            <div class="carousel-item">
                <img class="third-slide" src="https://www.pakutaso.com/shared/img/thumb/105TSURUTAMA20211_TP_V.jpg" alt="Third slide" height="80%" width="80%">
            </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</main>
<!-- 2column -->
<div class="main-contents wrapper">
<!--    左側部分    -->
    <div class="left-side">
        <h3 class="sub-title">エリアから探す</h3>
        <ul style="list-style: none;">
        {% for store in store_list %}
            <li><a href="{% url 'booking:staff_list' store.pk %}">{{ store.name }}</a></li>
        {% empty %}
            <li>まだ店舗がありません。</li>
        {% endfor %}
    </ul>
        <h3 class="sub-title">公開募集バナー</h3>
    </div>
<!--右側部分-->
    <div class="right-side">
        <h3 class="sub-title">お気に入り</h3>
            <ul class="sub-menu">
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="1">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="2">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="3">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="4">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="5">　</a></li>
            </ul>
        <h3 class="sub-title">新着スタイリスト</h3>
            <ul class="sub-menu">
            <div class="inlines">
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="1">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="2">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="3">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="4">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="5">　</a></li>
            </div>
            </ul>
        <h3 class="sub-title">ランキング</h3>
            <ul class="sub-menu">
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="1">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="2">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="3">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="4">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="5">　</a></li>
            </ul>
        <h3 class="sub-title">本日可能なスタイリスト</h3>
            <ul class="sub-menu">
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="1">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="2">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="3">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="4">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="5">　</a></li>
            </ul>
        <h3 class="sub-title">明日可能なスタイリスト</h3>
            <ul class="sub-menu">
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="1">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="2">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="3">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="4">　</a></li>
                <li class="inline"><a href="#"><img src="static/imgs/icon1.png" width="100" height="100" alt="5">　</a></li>
            </ul>
    </div>
</div>
<!-- 2column css -->
<style>
<!-- 左右で1:2 -->
.left-side{
    width: 34%;
}
.right-side{
    width: 66%;
}
.main-contents{
    display: flex;
    justify-content: space-between;
    margin: 30px 0 50px 50px;
}
li{
    list-style: none;
}
a{
    display: block;
}
.inline{
    display: inline-block;
}

</style>
{% endblock %}